version: "3"
services:
  web3:
    build: ./
    links:
      - db
    restart: on-failure
    environment:
      DEV_MODE: server_test
    volumes:
      - ./local:/var/www/local/
      - ./conf:/etc/apache2/sites-enabled/
      - ./ssl:/etc/apache2/ssl/
  web4:
    build: ./
    links:
      - db
    restart: on-failure
    environment:
      DEV_MODE: server_test
    volumes:
      - ./local:/var/www/local/
      - ./conf:/etc/apache2/sites-enabled/
      - ./ssl:/etc/apache2/ssl/
  redis:
    image: redis:3.2.10
    volumes:
      - "./data:/data"
    ports:
      - "6379:6379"
  db:
    image: mariadb
    volumes:
      - ./mysql-dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      #- ./mysql-dump:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker1234
      MYSQL_PASSWORD: docker1234
      MYSQL_DATABASE: cms
    ports:
      - "8889:3306"
    command: --sql_mode="" --innodb-flush-method=O_DSYNC --innodb-use-native-aio=0 --log_bin=ON
    tty: true
    privileged: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8082:80'
  loadbalancer:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      DEV_MODE: server_test
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/ssl/
    depends_on:
      - web3
      - web4
      - db